apiVersion: apps/v1
kind: Deployment
metadata:
  name: netherite-function
  labels:
    app: netherite-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netherite-function
  template:
    metadata:
      labels:
        app: netherite-function
    spec:
      containers:
        - image: <REFERENCE TO YOUR IMAGE>
          name: netherite-function
          ports:
            - containerPort: 80
          env:
            - name: AzureWebJobsStorage
              valueFrom:
                secretKeyRef:
                  key: AzureWebJobsStorage
                  name: secretfornetheritefunction
            - name: EventHubsConnection
              valueFrom:
                secretKeyRef:
                  key: EventHubsConnection
                  name: secretfornetheritefunction
            - name: WEBSITE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: WEBSITE_HOSTNAME
                  name: configfornetheritefunction
---
apiVersion: v1
kind: Service
metadata:
  name: netherite-function
  labels:
    app: netherite-function
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: netherite-function
  type: ClusterIP
status:
  loadBalancer: {}
